# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Теги')),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='yourblog.KeyWords', verbose_name='Ключевые_слова'),
        ),
    ]
