# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0003_auto_20180207_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='yourblog.KeyWords', verbose_name='Теги'),
        ),
    ]
