# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0004_auto_20180207_2107'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywords',
            table=None,
        ),
    ]
