# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0005_auto_20180207_2132'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keywords',
            table='keywords',
        ),
    ]
