# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0006_auto_20180207_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='1.jpg', upload_to='', verbose_name='Картинка'),
        ),
    ]
