# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0007_post_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(upload_to='', verbose_name='Картинка'),
        ),
    ]
