# Generated by Django 2.0.2 on 2018-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0009_auto_20180225_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
