# Generated by Django 2.0.2 on 2018-02-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourblog', '0010_calend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calend',
        ),
    ]
